config/routes.rb
Rails.application.routes.draw do

  resources :users
  
  resources :posts do
    resources :comments
  end

  root 'home#welcome'

  get '/login' => 'sessions#new' 
  post '/login' => 'sessions#create'
  get '/log_out' =>'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post

	validates :body, presence: true, length: { minimum: 5, maximum: 200 }
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	has_many :comments

	validates_uniqueness_of :username
	validates :email, confirmation: true, presence: true
	validates :password, confirmation: true, presence: true, length: { minimum: 5 }
	validates_presence_of :username, :fname, :lname, :email, :password, :country

	before_validation :ensure_username_has_a_value
	before_validation :normalize_username, on: :create

	protected
	 def ensure_username_has_a_value
	 	if username.nil?
	 		self.username = email unless email.blank?
	 	end
	 end

	 def normalize_username
      self.username = self.username.downcase.titleize
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
		@comment = Comment.new
	end

	def create
		Comment.create(body: params[:comment][:body], 
			post_id: params[:post_id], 
			user_id: session[:user_id])

		redirect_to	post_path(params[:post_id])
	end

	def edit 
		@comment = Comment.find(params[:id])
	end

	def update 
		@comment = Comment.find(params[:id])
		@comment.update(comment_params)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
		flash[:destroyed] = "Comment deleted"
	end

	private 
		def comment_params
			params.require(:comment).permit(:body)
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end

	def show
	end

	def new
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@post = Post.all
		if @post.present?
			flash[:notice] = "Post List"
		else
			flash[:alert] = "No Posts Found"
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def edit
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.create(title: params[:post][:title], 
				body: params[:post][:body], 
				user_id: session[:user_id])

		if @post.save
			flash[:posted] = "New post created"
		else
			flash[:correctPost] = "Please fill the form correctly. \n Title should contain at least 5 characters"
			render :new
		end

		# TESTING AJAX FORMS
		respond_to do |format|
			format.html { render 'postpost'}
		end	
	end

	def update 
		@post = Post.find(params[:id])
		@post.update(post_params)
		flash[:updated] = "Post updated"
		redirect_to posts_path
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		flash[:deleted] = "Post deleted"
		redirect_to	posts_path
	end

	private
		def post_params
			params.require(:post).permit(:title, :body)
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.find_by(email: params[:email])
		if @user && @user.password == params[:password]
			session[:user_id] = @user.id
			flash[:loggedin] = "You're now logged in"
			redirect_to root_path
		elsif session[:user_id] == nil
			flash[:nouser] = "No user found with those credentials"
			render :new
		else
			flash.now[:alert] = "Invalid email or password, please try again"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:loggedout] = "You've been logged out"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@user = User.all
		if @user.present?
			flash[:notice] = "User List"
		else
			flash[:alert] = "No users where found"
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def new 
		@user = User.new
	end

	def edit
		@user = User.find(params[:id])
	end

	def create
		@user = User.create(user_params)
			if @user.save
				session[:user_id] = @user.id
				flash[:created] = "New user created"
				redirect_to user_path(@user)
			else
				flash[:correct] = "Please fill out the form correctly"
				redirect_to new_user_path
			end
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		flash[:updated] = "User updated"
		redirect_to user_path	
	end

	def destroy 
		@user = User.find(params[:id])
		session[:user_id] = nil
		@user.destroy
		flash[:deleted] = "User deleted"
		redirect_to root_path
	end


	private
		def user_params
			params.require(:user).permit(:fname, :lname, :username, :email, :password, :country, :avatar)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="wrapper-high">
<p><%= comment.body %></p>
<p>Written by: <%= comment.user.username %></p>
<p><%= link_to "Delete", [comment.post, comment], data: { confirm: "Are you sure?"}, method: :delete %></p>
</div>

app/views/comments/_form.html.erb
<div class="wrapper-high">
	<h2>ADD A COMMENT</h2>
	<%= form_for([@post, @post.comments.build]) do |f| %>
		<p><%= f.label "Comment" %></p>
		<p><%= f.text_area :body %></p>
		<%= f.submit %>
	<% end %>
	<p><%= link_to 'Back', posts_path %></p>

	<br>
</div>

app/views/comments/edit.html.erb
<%= form_for(@comments) do |f| %>
	<%= f.label "Body" %>
	<%= f.text_area :body %>
	<%= f.submit "Update Comment" %>
<% end %>
  

app/views/comments/new.html.erb
<%= form_for(@comment) do |f| %>
	<%= f.field "Comment" %>
	<%= f.text_area :body %>
	<%= f.submit "Create Comment" %>
<% end %>
  

app/views/home/welcome.html.erb
<div class="wrapper">

	<% if session[:user_id] %>
		<h1>Hello User No. <%= session[:user_id] %>-198470!</h1>
		<h2>DO NOT BE AFRAID AND START POSTING STUFF HERE</h2>
		<h3>WE ARE NOT SPYING ON YOU</h3>
		<h3>TRUST US</h3>
		<h5>TRUST US</h5>
		<h6>TRUST US</h6>
		<i class="fa fa-user-secret"></i>

	<% else %>
		<h1>WELCOME</h1>

		<h2>This is literally a <strong style="color:red" >micro</strong> website testing the <br> usage of <strong style="color:red" > ruby </strong> on <strong style="color:red" > rails </strong></h2> 
	<% end %>

	<h3><%= flash[:loggedout] if flash[:loggedout] %></h3>
	<h3><%= flash[:loggedin] if flash[:loggedin] %></h3>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- INCONSOLATA -->
  <link href='https://fonts.googleapis.com/css?family=Inconsolata:400,700' rel='stylesheet' type='text/css'>
  <!-- ROBOTO -->
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,500,700' rel='stylesheet' type='text/css'>

  <!-- FONT AWESOME -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  
</head>
<body>

<div id="content">

<nav>
	<% if session[:user_id] %>
		<li><%= link_to "Home |", root_path %></li>
		<li><%= link_to "New Post |", new_post_path %></li>
		<li><%= link_to "All Posts |", posts_path %></li>
		<li><%= link_to "All Users |", users_path %></li>
		<li><%= link_to "Edit Profile |", edit_user_path(session[:user_id]) %></li>
		<li><%= link_to "Log Out", log_out_path %></li>

	<% else %>
		<li><%= link_to "Home |", root_path %></li>
		<li><%= link_to "Sign up |", new_user_path%></li>
		<li><%= link_to "Log in", login_path %></li>
	<% end %>
	
</nav>
<%= yield %>
</div>

<footer>
	<a href="https://github.com/joseap/railsblog" target="_blank"><h4><i class="fa fa-github-square fa-4x"></i></h4></a>
	<h4>everything is so small here</h4>
	<h4> <em>&copy; Jose Plata</em> </h4>
</footer>

</body>
</html>

app/views/posts/edit.html.erb
<%= flash[:updated] if flash[:updated] %>

<%= form_for @post do |f| %>
	<%= f.label "Title" %>
	<%= f.text_field :title %>
	<%= f.label "Body" %>
	<%= f.text_field :body %>
	<%= f.submit "Update" %>
<% end %>

app/views/posts/index.html.erb
<div class="wrapper-high">
	<h1>All Posts</h1>
	
	<hr>

	<h3><%= flash[:deleted] if flash[:deleted] %></h3>
	<h3><%= flash[:updated] if flash[:updated] %></h3>
	<h3><%= flash[:posted] if flash[:posted] %></h3>
	<h3><%= flash[:notice] if flash[:notice] %></h3>
	<h3><%= flash[:alert] if flash[:alert] %></h3>
	<br>

	<div class="post">
		<% @post.each do |post| %>

			<h1><%= link_to post.title, post_path(post.id)%></h1>
			<h3>By: <%= post.user.username %></h3>
			<p><%= post.body %></p>

			<h3><%= link_to "Comments", post_path(post.id) %> (<%= post.comments.count %>)</h3>
			<h3>Post created at: <%= post.created_at.strftime("%Y-%m-%d") %></h3>

			<% if post.user_id == session[:user_id] %>
				<h3><%= link_to "Delete", post, method: :delete, data: { confirm: "ARE YOU SUUUUUUURE?"} %></h3>
			<% end %>

			<hr>

		<% end %>
	</div>
</div>

app/views/posts/new.html.erb
<div class="wrapper-high">
	<div class="form">
		<h1> Create New Post </h1>

		<%= flash[:correctPost] if flash[:correctPost] %>

		<%= form_for @post do |f| %>
			<h2><%= f.label "Title" %></h2>
			<p><%= f.text_field :title, :class => "textfield" %></p>
			<h2><%= f.label "Body" %></h2>
			<p><%= f.text_area :body %></p>
			<%= f.submit "Create Post" %>
		<% end %>
	</div>
</div>

app/views/posts/postpost.html.erb
<div class="wrapper-high">
	<h2>You posted a post deeeeewd</h2>
</div>

app/views/posts/show.html.erb
<div class="wrapper-high">
	<h1>POST</h1>
	<div class="post">
		<h2><%= @post.title %></h2>
		<%= flash[:destroyed] if flash[:destroyed] %>
		<p><%= @post.body %></p>
		<br>
		<hr>
		<h1 class="wrapper-high">COMMENTS</h1>
		<%= render @post.comments %>
		<%= render 	'comments/form' %>
		</div>
</div>

app/views/users/edit.html.erb
<div class="wrapper-high">


<h1> UPDATE YOUR PROFILE </h1>
	<div class="form">
		<%= form_for @user do |f| %>
				<h1> PROFILE INFO </h1>
				<li><%= f.label "First Name" %></li>
				<p><%= f.text_field :fname %></p>
				<li><%= f.label "Last Name" %></li>
				<p><%= f.text_field :lname %></p>
				<li><%= f.label "Username" %>
				<p><%= f.text_field :username %></p>
				<li><%= f.label "E-mail" %></li>
				<p><%= f.text_field :email %></p>
				<li><%= f.label "Password" %></li>
				<p><%= f.text_field :password %></p>
				<li><%= f.label "Country" %></li>
				<p><%= f.text_field :country %></p>
				<%= f.submit "Update", class: "btn" %>
				<br><br>
		 	<%= link_to "Delete", @user, data: { confirm: "OMG, OMG, OMG ARE YOU FU£*!&@ SURE!?" }, method: :delete%>
		<% end %>
	</div>
	<hr>
	<br>
	<h1> USER POSTS </h1>
		<div class="post">
			<% @user.posts.each do |post| %>
				<p><%= post.body %></p>
				<h3>Post created at: <%= post.created_at %></h3>
				
				<% if post.user_id == session[:user_id] %>
					<h3><%= link_to "Delete", post, method: :delete, data: { confirm: "ARE YOU SUUUUUUURE?"} %></h3>
				<% end %>

			<% end %>
		</div>
		<br>
		<hr>
		<br>
		<h1> USER COMMENTS </h1>
		<% @user.comments.each do |comment| %>
			<p><%= comment.body %></p>
			<h3>Comment created at: <%= comment.created_at %></h3>

			<% if comment.user_id == session[:user_id] %>
				<h3><%= link_to "Delete", method: :delete, data: { confirm: "ARE YOU SUUUUUUURE?"} %></h3>
			<% end %>
	<% end %>


</div>

app/views/users/index.html.erb
<div class="wrapper-high">
	<h1> USERS</h1>

	<hr>

	<h3><%= flash[:created] if flash[:created] %></h3>
	<h3><%= flash[:deleted] if flash[:deleted] %></h3>
	<h3><%= flash[:alert] if flash[:alert] %></h3>
	<h3><%= flash[:notice] if flash[:notice] %></h3>

	<div class="list">
		<% @user.each do |user| %>
				<%= user.username %>	
		<% end %>
	</div>
</div>


		

app/views/users/new.html.erb
<div class="form">
	<h1>Create a New User</h1>

	<h3><%= flash[:correct] if flash[:correct] %></h3>

	<%= form_for @user, :url => users_path, :html => { :multipart => true } do |f| %>
			<h2>Upload profile pic</h2><h3>NOT optional</h3>
			<%= f.file_field :avatar %> 
			<br> 
			<h2> Enter your details </h2>
			<li><%= f.label "First Name" %></li>
			<p><%= f.text_field :fname, class: 'field' %></p>
			<li><%= f.label "Last Name" %></li>
			<p><%= f.text_field :lname, class: 'field' %></p>
			<li><%= f.label "Username" %></li>
			<p><%= f.text_field :username, class: 'field' %></p>
			<li><%= f.label "E-mail" %></li>
			<p><%= f.text_field :email, class: 'field' %></p>
			<li><%= f.label "Password" %></li>
			<p><%= f.password_field :password, class: 'field' %></p>
			<li><%= f.label "Confirm Password" %></li>
			<p><%= f.password_field :password_confirmation, class: 'field' %></p>
			<li><%= f.label "Country" %></li>
			<p><%= f.text_field :country, class: 'field' %></p>
			<%= f.submit "Create", class: "btn" %>
	<% end %>

	


</div>

app/views/users/show.html.erb
<div class="wrapper-high">
<h3><%= flash[:created] if flash[:created] %></h3>

<h3><%= "Welcome " + @user.username %></h3>
<h3><%= flash[:updated] if flash[:updated] %></h3>

	<h1> USER PROFILE </h1>
	<h2><%= label_tag "Username" %></h2>
	<p><%= @user.username %></p>
	<h2><%= label_tag "Name" %></h2>
	<p><%= @user.fname + " " + @user.lname %></p>
	<h2><%= label_tag "Email" %></h2>
	<p><%= @user.email %></p>
	<h2><%= label_tag "Country" %></h2>
	<p><%= @user.country %></p>
	<br><hr><br>
	
	<h1> USER POSTS </h1>
	<div class="post">
		<% @user.posts.each do |post| %>
			<p><%= post.body %></p>
			<h3>Post created at: <%= post.created_at %></h3>

			<% if post.user_id == session[:user_id] %>
				<h3><%= link_to "Delete", post, method: :delete, data: { confirm: "ARE YOU SUUUUUUURE?"} %></h3>
			<% end %>

		<% end %>
	</div>
	<br>
	<hr>
	<br>

	<h1> USER COMMENTS </h1>
	<% @user.comments.each do |comment| %>
		<p><%= comment.body %></p>
		<h3>Comment created at: <%= comment.created_at %></h3>

		<% if comment.user_id == session[:user_id] %>
			<h3><%= link_to "Delete", method: :delete, data: { confirm: "ARE YOU SUUUUUUURE?"} %></h3>
		<% end %>
	<% end %>



</div>